### ISSUE TITLE
Issue: -virtual Files not affected on Ubuntu 12.04

### ISSUE THREAD

**Issue by jesscetera** [rackerlabs/kthresher#12]
I noticed that the script did not seem to affect the -virtual files on an ubuntu 12.04 cloud server.

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 12.04.5 LTS
> Release:    12.04
> Codename:   precise

The files weren't being caught due this value not being 'kernel':

> $ dpkg -s linux-header-3.2.0-99 | grep Section
> Section: **devel**
> $ dpkg -s linux-header-3.2.0-99-virtual | grep Section
> Section: **devel**

So we had to change the 'and' to an 'or':

> (pkg.section == 'kernel' **or**
>             re.match(...))

**Comment by tonyskapunk** [comment]
Added support for "old" virtual kernel packages. 6ac4372

Virtual kernel packages were intended to be used for virtual instances but later deprecated(as it was intergrated) in favor of linux-image-generic as outlined in https://help.ubuntu.com/community/ServerFaq#What_are_the_differences_between_the_server_and_virtual_kernels.3F.

> Note: Since 12.04, there is no difference in kernel between Ubuntu Desktop and Ubuntu Server since linux-image-server is merged into linux-image-generic.
