### ISSUE TITLE
Feature request: implement daily cron job and /etc/default control of it

### ISSUE THREAD

**Issue by terackspace** [rackerlabs/kthresher#5]
We would like to implement a cron.daily (sic) script that runs kthresher as part of normal daily cron tasks. The implementation would include an /etc/default/kthresher configuration that has a setting that enables/disables the cron task, with the default set to 0 / no. Something like:

```
/etc/cron.daily/kthresher
-------------------------
ENABLED=0
if [ -f /etc/default/kthresher ]; then
  . /etc/default/kthresher
fi

/etc/default/kthresher
----------------------
ENABLED=0
```

...something like that, it's just a sketch. The spirit is that this is a possibly hazardous task to run for a given server that has an edge case not known about, and only after a local systems admin has tested in their configuration would they enable the cron task to run on schedule.

**Comment by tonyskapunk** [comment]
This can be handled in the control files e.g. `postinst` may need a discussion to find where is the best place for this.
