### ISSUE TITLE
Document default configuration option values

### ISSUE THREAD

**Issue by jkirk** [rackerlabs/kthresher#68]
The default value of the configuration options should be mentioned in the configuration sample, man page and help output.

These files are affected:
https://github.com/rackerlabs/kthresher/blob/master/kthresher.conf#L7-L12
https://github.com/rackerlabs/kthresher/blob/master/kthresher.py#L287-L305
https://github.com/rackerlabs/kthresher/blob/master/kthresher.8

**Comment by tonyskapunk** [comment]
@jkirk I tagged you in #69 for a review, let me know if there is anything else missing.
